-- 创建面试会话表
CREATE TABLE IF NOT EXISTS interview_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  start_time TIMESTAMPTZ DEFAULT NOW(),
  end_time TIMESTAMPTZ,
  posture_score INTEGER,
  expression_score INTEGER,
  eye_contact_score INTEGER,
  overall_impression TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 添加索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_interview_sessions_user_id ON interview_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_interview_sessions_start_time ON interview_sessions (start_time);
