-- 创建面试观察记录表
CREATE TABLE IF NOT EXISTS interview_observations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  observation_type TEXT NOT NULL, -- 'expression', 'eye_contact', 'head_pose', 'gesture'
  observation_value TEXT NOT NULL, -- 'smile', 'frown', 'neutral', 'left', 'right', 'center', 'forward', 'backward', 'tilted', 'upright'
  message TEXT NOT NULL, -- 面试官观察到的具体描述
  severity TEXT NOT NULL, -- 'positive', 'warning', 'negative', 'neutral'
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 添加索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_interview_observations_user_id ON interview_observations (user_id);
CREATE INDEX IF NOT EXISTS idx_interview_observations_session_id ON interview_observations (session_id);
CREATE INDEX IF NOT EXISTS idx_interview_observations_timestamp ON interview_observations (timestamp);
